image: /home/alumno/turtlebot3_ws/src/proy_techcommit/proy_techcommit_my_nav2_system/config/my_map.pgm
mode: trinary
resolution: 0.05
origin: [-40.6, -31.7, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25